name: Windows-Server-2025
on:
  workflow_dispatch:
  push:
    branches: [master]
    paths: ['windows-server-2025.pkrvars.hcl']
jobs:
  build:
    uses: ./.github/workflows/packer.yml
    with:
      name: windows-server-2025
      vm_id: 1019
      os_type: windows
    secrets:
      proxmox_host: ${{ secrets.proxmox_host }}
      proxmox_user: ${{ secrets.proxmox_user }}
      proxmox_password: ${{ secrets.proxmox_password }}
